version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  CICD:
    docker:
      - image: 'cimg/node:16.15.0'
    steps: 
      - node/install
      - checkout
      - eb/setup
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
     
      - run:
          name: Install Backend dependencies
          command: npm run bkend-directory&&npm run bkend-install
      - run:
          name: Install Frontend  dependencies
          command: npm run frend-directory&&npm run frend-install

      - run:
          name: backend build
          command: cd udagram-api&&tsc&&npm run build
     
      - run:
          name: Frontend build
          command: cd udagram-frontend&& npm run frend-build
      - run: 
          name: Backend test
          command: npm run bkend-directory&&npm run bkend-test
      - run:
          name: Frontend test
          command: npm run frend-directory&&npm run frend-test
      - run:
          name:  Backend deploy
          command: npm run bkend-deploy-directory && npm run bkend-deploy
      - run:
          name: Frontend deploy
          command: npm run frend-deploy
     
workflows:
  build-deploy:
    jobs:
      - CICD:
          filters:
            branches:
              only: [main]

